package com.abin.lee.sharding.jdbc.mapper.business;

import com.abin.lee.sharding.jdbc.entity.Business;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    Business selectByPrimaryKey(Long businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Business record);


    List<Business> findByUserId(@Param("userId") Integer userId);

}